# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6aa87392319186f529a2413f2e3c629d10f08c63d72288cf8eb114a9cbb317abc00f002ca821a9b2e85a21f931c81776026aea608bb8e8d82b3dcf9f73e2565a

test:
  secret_key_base: ce2a5cc564861c55ec3997bb7ae140963bdc8fe1e28eae33959e6a62bf3ae043d3e889099146bc71b3062817fdbf54105257edfd605b8f3e046e6da0f7fbd1a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
